### ISSUE TITLE
Version 7.x based on version? and upgrade question.

### ISSUE THREAD

**Issue by WayneM1** [bhadaway/stop-spammers#1]
Is version 7.x based on the stable beta version 6.16 from Keith's beta plugins page, or from an earlier version? I'm using v6.16 and do not want to lose any of that version's functionality.

Also, I noted a brief instance of the changelog stating that the upgrade to ver 7.0 would lose settings (and to be sure to save settings before upgrade). There is not a feature in the 6.x versions of the plugin to save or export settings. So, do I need to note all my current settings manually if I want to retain those?

Finally, thanks for taking on the responsibility to keep this fantastic plugin alive and up to date :-)

**Comment by bhadaway** [comment]
Hey Wayne,

Yes, 7.0 is based on the latest version Keith was working on (6.16) and even further along than that. It's mostly an overhaul and cleanup of the presentation: code, design, wording, etc., and a few fixes. But the foundation is still the same.

There was indeed a brief moment though where it looked like 7.0 would be a major enough upgrade, that it would be a disconnect from older versions (hence the warning), but Keith came up with a simple and elegant solution to automatically port over the old settings.

I've tested it on a few sites now and it worked flawlessly. That said, you never know, so as annoying as it is, I have to give you the obligatory "It's better to be safe, than sorry." speech about how it's always best practice to back things up before updating stuff (though, of course, most people don't, like most people don't read the fine print). ;)

So, there, I've given you the best practice speech. Otherwise, it's up to you. If you do back up, you will indeed need to manually copy them out to a text file.

As for the future of the project, absolutely. I love this plugin and have appreciated Keith's hard work on it for a long time. He had already mentioned retiring his maintenance/development of it in the past and I offered to take over. But when it got knocked off of wordpress.org recently, it was really time to jump in. This plugin is invaluable and I'm honestly surprised it's not one of the plugins in the million+ users club.

Anyways, Keith isn't completely gone from the project and has been helping me make sure it's a smooth transition. I think, off and on, he'll still pop in to add fixes and improvements for some time to come. But, concerning the day-to-day, I'll try to lift the burden of general support and maintenance as much I can. I think getting it on GitHub will also help keep bugs and whatnot in check.

Thank you.
