### ISSUE TITLE
This address is invalid for testing for the following reason: IP same as server: 

### ISSUE THREAD

**Issue by homes2017** [bhadaway/stop-spammers#10]
I just changed hosting companies and get the error in this post's title. Similar issue with another plugin (Wordfence) in that all traffic being reported as the server IP. Wordfence has an option for X-Forwarded-For, when selecting resolved the IP issue.

Wordfence's X-Forwarded-For selection is for host using a forward proxy (not sure what that is).

Is there a way to incorporate X-Forwarded-For, for Stop Spammers?

Or is there another setting to address this?

**Comment by bhadaway** [comment]
Sounds like you're using Varnish. See here:

https://github.com/bhadaway/stop-spammers/issues/8

**Comment by homes2017** [comment]
I don't think so. Namecheap is the host.

**Comment by bhadaway** [comment]
Varnish is not a hosting service; it's a caching solution. When Stop Spammers can't properly detect the user's public IP, this is usually because of some caching solution like Varnish or Cloudflare being in place for the website. In both cases, special steps need to be taken in order to restore user IPs.

You may want to check with your host's support or webmaster (of you have one) to see if any caching solutions are being implemented for your site or anything else which might stop you from being able to detect user IPs normally.
