### ISSUE TITLE
Blocklist and jolly character

### ISSUE THREAD

**Issue by karnhack** [bhadaway/stop-spammers#101]
Hi,
I can create a filter with multiple “jolly character”?

`eg. *Accout@*
`

in my case I would like to prevent you from registering for these emails:

ginaAccout@gmail.com
ninaAccout@yandex.ru
jerryAccout@excite.com
etc
etc

**Comment by bhadaway** [comment]
Hmm, I'm not sure that would work.

Under: _Stop Spammers > Block Lists_, trying adding **Accout** and **yandex** to the _Spam Words List_ and add **.ru** to _Blocked TLDs_.

Are there any other reoccurring patterns with this spam, like perhaps the IPs are coming from a specific country? If so, _Stop Spammers > Protection Options > Block Countries_ might help.

**Comment by karnhack** [comment]
The spammer uses different ip and email addresses ... the only common thing is the term Accout present in all his emails xxxAccout@domain.ext
It's giving me a lot of trouble

**Comment by bhadaway** [comment]
Yes, I assumed the IPs would be different every time. That's to be expected. However, it's possible, even likely, that they're still coming from the same general region.

You can check them here to see if you can narrow that down:

https://whatismyipaddress.com/ip-lookup

**Comment by karnhack** [comment]
I did as you suggested. I blocked the Russian federation. I also blocked his ip 195.208.220.174but he has created other false accounts with the same ip... O_O
He's persecuting me...

**Comment by bhadaway** [comment]
Rest-assured that it's _very unlikely_ that you're being personally targeted.

If you were, you either wouldn't have anything on your radar at all because they would very quietly be campaigning against you OR you would definitely know for sure because they would be overtly harassing you through all available avenues: email, social media, etc.

This is just an automated spam bot, that all website owners, especially those running WordPress, have to deal with. Here are some additional protections that I recommend:

https://github.com/bhadaway/stop-spammers/wiki/Recommendations

And if you're still struggling, you're welcome to email me for a private consultation.
