### ISSUE TITLE
ERR: cURL error 6: Could not resolve host: www.stopforumspam.com

### ISSUE THREAD

**Issue by mattpark22** [bhadaway/stop-spammers#102]
We are frequently getting "ERR: cURL error 6: Could not resolve host: www.stopforumspam.com" in our logs, and I can see genuine users are being blocked for this reason, is there a way around this? If cURL fails on the third party for any reason, can we give the user the benefit of the doubt?

**Comment by bhadaway** [comment]
What host are you on and do you know what kind of server OS it is (Windows/Linux)?

**Comment by mattpark22** [comment]
We are hosting the website on TSO Host's cloud hosting shared platform, Linux based. SFS works often, but at times fails with the cURL error 6 often for an entire day, like a firewall temp ban. Is it possible to handle this better if cURL happens, so it doesn't disrupt the user logging on?

**Comment by mattpark22** [comment]
This screenshot helps explain the issue a little better, 1 request will work, then next minute it fails, and this causes user login issues. 
![sfs_issue](https://user-images.githubusercontent.com/8157430/63155965-99432b00-c00b-11e9-9beb-bffd8e6f3189.jpg)

**Comment by bhadaway** [comment]
I haven't seen this issue before, but I suspect it might be an issue to do with the shared host IP, which these IPs usually find their way onto blacklists because there's bound to be at least one website, if not several in the pool of hundreds of websites that's up to something naughty.

It's iffy, but getting a dedicated IP might help. Many hosts allow you to purchase your own private, dedicated IP (read: less likely to have been used and abused, and therefore, clean). Most hosts let you purchase a dedicated IP even while remaining on the cheap shared hosting tier for mere dollars.

Could be worth a try, and there are other benefits to this upgrade even if it doesn't work, like improved quality in your email reaching inboxes for example. I'll re-open if it doesn't help.
