### ISSUE TITLE
Allow countries option

### ISSUE THREAD

**Issue by PINKbyPuck** [bhadaway/stop-spammers#107]
I am getting a lot of false positives.

Is there a way that I can allow just a few countries, instead of blocking a bunch.
It's more accurate to allow 5 (as an example) then to block all but 5.

Thank you.

**Comment by bhadaway** [comment]
I understand what you mean, but the problem is that the Block Countries feature doesn't actually block entire countries, it just blocks known bad IP ranges. But yes, this is indeed risky for causing false positives.

Can you describe in more details the specific spammers you're trying to block? Perhaps we can find a more elegant solution to deal with them than blocking country IPs.

**Comment by PINKbyPuck** [comment]
Is there a way to block all but people from the NL and BE? Because that's all I need, people that are situated in the NL/BE are the only clients that will even be needing acces.
The website is completely in Dutch so no one else will understand anyway.
Now I cannot really understand why some people are being blocked. So maybe I'm just being too strict in my settings, but since I don't know which setting is causing the block I have no clue where to begin.

If I could only accept people from these countries, then I would just turn everything else off and most of the issue will be gone, I think/hope.

**Comment by bhadaway** [comment]
Are you looking to only allow people physically located in the Netherlands or Belgium, or are you only looking to allow people who speak Dutch? That's a very important distinction, and dangerous if we get it wrong.

If you're just intending to support those who speak Dutch, they might not necessarily live in just NE or BE, or they might be traveling, or they might be using a VPN, as just a few examples that could get them blocked. Similar issues apply for only allowing people located in NE and BE.

Again the Block Countries feature is just for known problematic IPs; it's not the actual complete IP list for the country. For example, Netherlands has 50+ million IP addresses:

https://lite.ip2location.com/netherlands-ip-address-ranges

If you just whitelisted the entire country, which may have other practicality issues, it would be very dangerous, because a lot of spammers are going to be let in that way. You might solve the false positives issue, but you'll open the flood gates on spam registrations and be in much worse trouble.

I think you should unblock all countries and focus on fine-tuning other settings.

Alternatively, if you're too frustrated to keep fussing, you're welcome to contact me for a private consultation, so that I can get in their and personally investigate the problem:

bhadaway@gmail.com

**Comment by PINKbyPuck** [comment]
Hi Bryan,

This is primary for people actually situated in the Netherlands.
However, I do foresee some issues with big hosting or network companies and
maybe VPN.
I know for example that I worked at an American company once, and my IP on
the work computer was therefore registered as American.

But the spammers are by nature, rarely situated in the Netherlands, so that
would not really be an issue.

We'll keep it as it is for now.  I'm not really in understanding with all
the other options, so probably there is a lot of finetuning to do there.
Thanks for helping me out anyways.

Groetjes,
Puck
*PINK by Puck*  *·  **WordPress Websites *
Puck Verest
Oirschot  *·  *Den Bosch
06-1299 4945 <0612994945>

**Comment by bhadaway** [comment]
You can always add some additional plugins to help keep bad behavior under control without having to fuss with country blocking:

https://github.com/bhadaway/stop-spammers/wiki/Recommendations

If you need me, I'll re-open this issue.
