### ISSUE TITLE
Email notification to the user about Allow Request accepted

### ISSUE THREAD

**Issue by SergeySch** [bhadaway/stop-spammers#11]
Hi,

is it possible to send email notification to the user when his record was added allow list at the "Allow Requests" page? So he/she will know that can log in now. 

I can't find such option in the plugin settings.

**Comment by bhadaway** [comment]
This is not currently possible, but it's a good idea. I've labeled it as "enhancement," which in this case, means it'll remain as a request or wishlist item for possible future implementation.

For now, you'll need to manually update users. However, I may implement a more practical lightweight solution in terms of letting such users know:

"Your request has been received. Please check back within 24 hours to log in again. Or you may email support directly at email@website.com."

Something to that effect.

**Comment by SergeySch** [comment]
Here is my attempt to do it -  #[12]
But really not sure if it fit in the plugin/wordpress structure.

**Comment by bhadaway** [comment]
Thanks Sergey!

I'd need to spend some time with it for a while to see if the feature should be officially included. For now, I think using your own customized version and pointing people towards https://github.com/SergeySch/stop-spammers if they want to try out the feature is probably the way to go.

Philosophically, my goal for the official Stop Spammers plugin might be to go even more minimalist and focus on just the key features. My main goal since taking over was just to keep the project alive and give it some fresh updates and get people like yourself interested and to help contribute.

I'll carefully review and test the plugin more soon.

**Comment by mchinsky** [comment]
I also 2nd this request.  It's crazy that the user has no way of knowing they are approved and i have to manually spend time for every approved person to let them know they can come back.  Most will forget about it and never return without a notification.

**Comment by bhadaway** [comment]
Concerning trying to consolidate this plugin and keep it more lightweight and less of a memory hog, I think I want to avoid the plugin emailing anyone except for the admin. And even then, at a bare minimum.

For large sites with a lot of traffic, this could become a problem, but if spammers are getting approved, sending email out to them could cause the opening of yet another can of worms as well.

Believe me, I understand. I've run Stop Spammers on large e-commerce sites in the past and the concern for losing customers based on them being blocked is real. But emailing people and them being annoyed and going for the spam button, diminishing your email and server reputation, is a real problem too.

Lots of pros and cons, but I think fine-tuning your spam and security measures both for the kind of legitimate and spam users you get, is a better approach. It's always about finding that balance between convenience and security.
