### ISSUE TITLE
Stop Allow Request Emails

### ISSUE THREAD

**Issue by CharlieLivingston** [bhadaway/stop-spammers#32]
Is there a way to stop the plugin sending Allow Request emails? They are quite numerous. 

Edit: I found the option in the plugin: 'Blocked users can add their email addresses to the the Allow List request. This will also send you an email notification'.

But what I really want is for them to be able to include an email (so I can email the promising sounding ones and check) but I don't want an email notification every time. Is this not possible?

**Comment by bhadaway** [comment]
It already works this way.

Disabling the email notification won't change the behavior of the Allow Requests. They'll still appear in the list under _Stop Spammers_ > _Allow Requests_ where you can see email addresses and other info in order to decide if they're legit or not.

Usually it's pretty obvious which ones are spam and you can deny or delete them out. Then for ones that are obviously real people or you're not sure, you can either approve or contact them for further verification.

Additionally, you'll probably notice patterns emerge for email domains and whatnot where it's always spam and never a legitimate user. In that case, you can go to _Stop Spammers_ > _Block Lists_ and block them even more aggressively, so they can't even make the request.

Thanks
