### ISSUE TITLE
Allow Country

### ISSUE THREAD

**Issue by alebyo** [bhadaway/stop-spammers#4]
Is it possible to allow users from a certain country?
For example, users from country A are not spam checked, everyone else is spam checked.

The plugin is working great, but seems to be stopping some real users.

Thank you

**Comment by bhadaway** [comment]
Instead of blocking a country, you're looking to whitelist an entire country (as much as is possible anyways)?

While this is of course dangerous, and will probably open you up to a spam headache that's much worse than having to manually allow people when they get trapped in the spam filter (I imagine that's what you're trying to solve), I'll look into it.

However, I should note: no matter what you do, there are always going to be false positives; real people are always going to get stuck in the filter; just like legitimate emails will every once in a while get sent to your Spam folder. This is true of all spam-prevention software.

**Comment by alebyo** [comment]
Thank you for the reply. 
My site is Japanese and 90% of users are from Japan. 
I'm getting 20 or so fake registrations per day from obvious non-Japanese users which the plugin has stopped, but now some real users from Japan have emailed me that they cannot login. I have allowed these user's IPs but think new users that might get blocked would just not come back to the site. 
I'm guessing spam registrations from Japan would be limited and would prefer to just let everyone from this country in instead of risking rejecting a user. 
Thanks again.

**Comment by bhadaway** [comment]
Okay, the CIDR format generated from https://www.countryipblocks.net/country_selection.php for the country you want to allow, added to the Allow List might work. And then you might also check the boxes to block all other countries in the settings.

However, I'm nervous and skeptical about this approach. It's a lot of data and could slow Stop Spammers or even your site down. An .htaccess approach might be better to help batten down the hatches.

Japan IPs: https://pastebin.com/VHQy3kW0

.htaccess Spam Prevention: https://perishablepress.com/tag/blacklist/

You might want to do some before and after speed tests on your site to make sure things haven't gotten too heavy.

**Comment by alebyo** [comment]
Thank you for the reply. 

If I simply copy and paste all the IPs from https://pastebin.com/VHQy3kW0 into the allow list, do you think that would slow a site down?

I don't want to completely block other countries, I still get some Japanese users from outside of Japan.

**Comment by bhadaway** [comment]
Let me run a quick test...

**Comment by bhadaway** [comment]
Alright, I'm not exactly working in a laboratory setting, but it doesn't seem to noticeably impact speed or cause any other catastrophes, in my tests at least. It still feels like a "heavy" solution to me, but you'd be the real-world test for that.

After implementing the solution, you'll want to check:

1. That it's not causing any load issues.

and

2. That it actually solves your problem.

If there are no load issues and your problem is solved, awesome.

If there are no load issues, but it doesn't solve your problem, just remove the IPs, and we'll have to investigate further.

If there are load issues, but the problem is solved, feel free to email me privately (bhadaway@gmail.com) if you'd like me to take a look at helping you optimize your site for speed.

And last, but not least, remember, if it does work in the sense of whitelisting a whole country, as you've asked, that may very well backfire and open you up to even more spam than before. So, we'll have to wait and see. :P

**Comment by alebyo** [comment]
Thank you for all the replies/advice. I have pasted the IPs into the plugin and for now pagespeed tests with google devs and webpagetest.org seem to be giving almost the same results. I will let you know how things go.

**Comment by bhadaway** [comment]
How's it working?

**Comment by alebyo** [comment]
Hi Bryan, so far so good although I haven't had any new sign-ups. Maybe
wait around a month and I'll let you know. Cheers

**Comment by bhadaway** [comment]
Alright. I'll close for now, but if any issues pop up, drop back by and I'll re-open the issue. Thanks.
