### ISSUE TITLE
Access Denied This site is protected by the Stop Spammer Registrations Plugin.

### ISSUE THREAD

**Issue by dgreatblack** [bhadaway/stop-spammers#5]
This plugin logged me out of my site. Though I was warned when I was installing it that it may occur but I was also given a safe link that i can use to recover and get back to my site. But the link seems not to be working. The plugin has refused, it's a bloody badass. How can I escape this? And I really need the plugin, it works 100%. I know I can delete or rename it from my File Manager. But after that how can i get it to work as normal?
*Yes, I changed that email in my WP Dash says that "for admin purposes" i had to change it to the site name instead of my personal mail, because it sends it to people after registration.
*I have tried to send a mail to my self as it said but still no way.

> See attached

![screenshot 151](https://cloud.githubusercontent.com/assets/28790396/26243926/8f0ec63c-3c85-11e7-8a21-5904322db897.png)

**Comment by ldch1000** [comment]
Oddly had the same problem on my ipad this morning.  It refused to let me sign in to my own site.  First time this plugin has done this.  I am the admin and a registered user and it was denying me.  Arrg.  Oddly, it didn't stop me signing in from my phone.  So i got in that way and  deactivated it and it will stay that way until I know more about why after years of using it, it did this. I adore this plugin.  I hope it can be fixed soon.

**Comment by bhadaway** [comment]
In this particular case, it's all about IP addresses. Not the usernames, devices, etc. The right public IP addresses that you use from your personal computer, tablet, or phone, are what need to be whitelisted.

@dgreatblack In your case, the solution is not pretty and too advanced for most users. You're going to need to go into MySQL and manually whitelist yourself. Do you have access to this tool via your host account? Are you comfortable giving it a try? If so, I'll try and walk you through.

@ldch1000 Normally, all the devices you use in your home, workplace, or wherever, are going to share the same public IP. Therefore, whitelisting that one address will whitelist all those devices.

However, in your case, it sounds like you originally signed in with your phone and/or installed Stop Spammers with your phone? My guess is that your phone is using a separate network and is not connected to the same WiFi that your tablet is?

On your tablet, go to https://www.google.com/search?q=ip. Then, log into your site with your phone and whitelist that address. Now, try logging in with your tablet again.

Thanks

**Comment by dgreatblack** [comment]
since that's the only way to escape this you should have proceeded with the How To. How can I safely whitelist my IP from sql?
@bhadaway

**Comment by bhadaway** [comment]
@dgreatblack Please do remember that this is a free plugin and any help you receive is only as a courtesy in someone's free time, on a volunteer basis. We neither should nor shouldn't do anything.

I would much rather make sure that someone is even willing and comfortable to attempt an advanced fix, before I spend the time researching, testing, and writing a solution.

That said, this seems to be one of the biggest issues over the years with the plugin and I'm not sure if the previous developer ever wrote up a how-to on this (probably for all the obvious cans of worms it opens and potential for people to break their sites even worse). Even so, it's probably a good idea to write this solution for future reference anyways.

_Please be careful. Please make a backup before proceeding. Attempt this solution at your own risk._

1. Log into phpMyAdmin. This will be different for every host (if they even offer you access in the first place). You may need to contact your host's support or browse their documentation.

2. Navigate to the database which is storing and serving data for the website in question that you're locked out of with Stop Spammers. If you're not sure, you can find the database name in your _wp-config.php_ file. Most likely you'll need a File Manager or FTP access to navigate to and retrieve this file. Again, you may need to contact your host's support or browse their documentation.

3. Go to the "_Search_" tab, enter **ss_stop_sp_reg_options**, click "_Select all_" to search all tables, and then click "_Go_."

4. Click "_Browse_" next to **wp_options** (the prefix _wp__ might be something else if you changed this in _wp-config.php_ when you or someone else first installed WordPress.

5. Now click "_Edit_" next to the row named **ss_stop_sp_reg_options**.

6. Hit _Control+F_ (PC) or _Command+F_ (Mac) and search for **"wlist"** (including the quotation marks).

7. Replace the very first IP address you find that appears _after_ **"wlist"** with the one you're currently using to try and access your site and click "_Go_." You can always quickly grab your current public IP by simply searching for "[ip](https://www.google.com/search?q=ip)" in Google.

8. You should now be able to log back into your site. Once you're in, I strongly recommend going through your entire Stop Spammers settings, page by page, making sure everything is good, and make sure to whitelist all the IPs of all admins and the various homes and workplaces, and devices therein, that they need access to the site from.

Let me know if you have any concerns or follow-up questions before proceeding. Please let me know if it works.

Thank you.

**Comment by dgreatblack** [comment]
I give up. This thing has started to behave like it has a brain. I replaced the IP i saw there with my IP and saved it. It didn't give me access to my site. I checked again, i didn't see any IP at all. I re-entered my IP, saved it, and i didn't see it. Now i believe that some AI can go evil one day. i am deleting it by the way, maybe a less evil one will come one day.  ;)

@bhadaway i really understand that the plugin is free and all that , but it would give you and i great joy if we see the problem solved. I know you will be very happy to hear that your solution worked, it should work, i jusat don't understand. But the plugin is die hard. i wish i could repay you for your time and effort. just mention it.. :) :+1: :1st_place_medal:  thanks

**Comment by dgreatblack** [comment]
Even with the permission set to 0000 in File Manager, i still can't login. After requesting for new password it will say that the password is incorrect. Anybody knows how I can login to my site?

**Comment by bhadaway** [comment]
@dgreatblack I was already going to ask if you're using a VPN, ad-blocker, etc. (the things that can trip up a spam filter into thinking a legitimate user is a bot), but from your screenshot, it appears you are indeed using some kind of plugin of this nature? Where it says: "IP : Failed!" You might want to try using a browser with such proxies/add-ons disabled and then try logging in.

At this point, I suspect that's still not going to work, so I have one final suggestion: doing a complete wipe and fresh install of Stop Spammers.

1. Delete the **/stop-spammer-registrations-plugin/** folder from _/wp-content/plugins/_.

2. Get back into phpMyAdmin and completely delete out **ss_stop_sp_reg_options** and **ss_stop_sp_reg_stats** from _wp_options_.

3. Now, make sure to install and activate the very latest version of Stop Spammers from https://wordpress.org/plugins/stop-spammer-registrations-plugin/.

4. Since you should now be in your /wp-admin free and clear while Stop Spammers is installed, take advantage of this opportunity to go through the options and make them fail-proof for yourself as much as you can. If clearing your IP isn't working, my guess is that it's constantly changing for one reason or another. Or if not, there's something in your internet-browsing set up that's triggering the lock-down.

You may want to adjust the following settings:

— _Stop Spammers_ > _Protection Options_ > _Uncheck "Check Credentials on All Login Attempts"_

— _Stop Spammers_ > _Allow Lists_ > _Check the box at the top and add your username to the list_

If you still get locked out, I'll be at a loss. You'll have to rinse and repeat the fresh install and try again, or it might get to the point where you're weakening the plugin so much just to accommodate yourself not getting locked out, that it deems the plugin pointless. At that point, you'll probably have to start exploring alternatives:

https://wordpress.org/plugins/search/spam/

Good luck!

**Comment by dgreatblack** [comment]
Ok. This worked. The best fail safe method. Thanks a lot for your support.

**Comment by bhadaway** [comment]
Happy to hear. You're welcome. :)
