### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by TheGeekGoddess** [bhadaway/stop-spammers#7]

**Comment by bhadaway** [comment]
That's not a bad idea, but I don't believe that's possible at the moment. The key is usually to pick out the most unique/spammy word that shouldn't otherwise show up in normal conversation. What's the spam phrase that's getting posted?

**Comment by TheGeekGoddess** [comment]
It's various spammers who keep promoting SEO services. They always reference the page title in their post, so I wanted to be able to block the page title (which is a phrase and not a single word).

**Comment by bhadaway** [comment]
That seems like overkill and not an easy solution to maintain in the long-run. If your website has nothing to do with SEO, and you don't imagine ever discussing SEO with your readers, simply blocking "SEO" would be the way to go.

If it's something that does come up or might come up organically, can you please share a copy of one of the comments, the: name, email, and entry? I might have a more unique suggestion.

**Comment by TheGeekGoddess** [comment]
Well, I'm a website developer, so yes, SEO would come up. :) Believe me, I looked at all the words they were commonly using in their spam posts to see if there was something unique I could use. I actually don't have a ton of posts, so it would have been easy to maintain. The name and email changes all the time (as does the IP), so I was looking at some other way. It's more of nuisance than anything, but if I can't block via a phrase I can live with it. Also a BIG thanks for jumping in and helping with this project!

**Comment by bhadaway** [comment]
I'll leave this open with the label "enhancement" because I think it could be a useful feature to add. Still, the plugin should be robust enough to handle this. I'm really surprised they're getting through. Can I ask, have you also integrated Akismet and Cloudflare? That might close the gap.

Anyways, you're very welcome, but keep in mind that as a big user of the plugin myself, it's very self-serving to make sure it survives cause I couldn't live without this plugin :). It's really a must-have for any WordPress site, especially ones that allow open registration and commenting.

**Comment by paulzag** [comment]
I know those sort of spam comments. Normally they quote the title of the blog post or the blog name or url 

e.g. It starts with "This software will get more clients and sales for marriageworks.com.au"

Would a legit commenter be adding the blog url in a comment?

If not then maybe the feature request is a setting to flag the comment if it contains the Blog name/url or post name/url?
