### ISSUE TITLE
Request: Support servers behind a load balancer

### ISSUE THREAD

**Issue by dfeemster** [bhadaway/stop-spammers#71]
We use servers on AWS and their ELB load balancer.  The $_SERVER['REMOTE_ADDR'] variable is always the IP of the load balancer, but the load balancer adds a "HTTP_X_FORWARDED_FOR" header with the actual IP address.  Stop Spammers only looks at $_SERVER['REMOTE_ADDR'] for the IP, so it doesn't work very well for us right out of the box.

I made a change and replaced the ss_get_ip() function with one that I found that checks common headers.  I added calls to this function in 3 places in the plugin that requested $_SERVER['REMOTE_ADDR'] directly.  

This worked great for me.  Is it something that you would consider making standard?  I guess that the downside is that it's easier to spoof a header than "REMOTE_ADDR", but in my case this var is useless.

The following is the function that I used.  Looks like it is a similar to the Wordpress get_unsafe_client_ip() function from class-wp-community-events.php.

function ss_get_ip()
{
    if ( isset($_SERVER['HTTP_CLIENT_IP']) ) {
        $ip = $_SERVER['HTTP_CLIENT_IP'];
    } else if ( isset($_SERVER['HTTP_X_FORWARDED_FOR']) ) {
        $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
    } else if ( isset($_SERVER['HTTP_X_FORWARDED']) ) {
        $ip = $_SERVER['HTTP_X_FORWARDED'];
    } else if ( isset($_SERVER['HTTP_FORWARDED_FOR']) ) {
        $ip = $_SERVER['HTTP_FORWARDED_FOR'];
    } else if ( isset($_SERVER['HTTP_FORWARDED']) ) {
        $ip = $_SERVER['HTTP_FORWARDED'];
    } else if ( isset($_SERVER['REMOTE_ADDR']) ) {
        $ip = $_SERVER['REMOTE_ADDR'];
    } else {
        return '';
    }

    if ( strpos($ip, ',') !== false ) {
        $ips = explode(',', $ip);
        $ip = trim(@$ips[0]);
    }

    if ( function_exists('filter_var') ) {
        return filter_var(
            $ip,
            FILTER_VALIDATE_IP
        );
    }

    return preg_replace(
        '/[^0-9a-f:\., ]/si',
        '',
        $ip
    );
}

**Comment by bhadaway** [comment]
I think a better approach would be to restore visitor IPs at the server level rather than altering every third-party tool to accommodate your setup.

In other words, it's not just Stop Spammers, there are lots of logging, analytics, spam/security tools that will be rendered useless (or at least much less useful) because they're not recording actual IPs.

This tutorial appears to be very close to what you need:

https://geekflare.com/client-ip-aws-elb-behind-cloud-flare/

Here's an official AWS doc:

https://aws.amazon.com/premiumsupport/knowledge-center/log-client-ip-load-balancer-apache/

There are several other help threads and links discussing the issue as well:

https://forums.aws.amazon.com/thread.jspa?threadID=62474
