### ISSUE TITLE
Does this plugin use cookies on my website or collect info about users? 

### ISSUE THREAD

**Issue by RebeccaGw** [bhadaway/stop-spammers#72]
Does this plugin use cookies on my website or collect info about users/website vistors? Thanks.

**Comment by bhadaway** [comment]
Yes.

It logs a number of pieces of info:

- IP address
- Username
- Email address
- Browser user agent
- Etc.

But, it only retains this info if it needs to, if it caught a spam bot it could add that info to the bad cache or block list, and if someone needed to be cleared, to the good cache or whitelist.

All this data is only saved in a very limited and generally, very temporary kind of way. Considering every website you visit records this data by default anyway, I'm not sure I can see how it could be an issue or require any special notice for the GDPR or otherwise.

Any generic privacy notice that already discloses that visitor IPs are recorded, I should think would adequately cover Stop Spammers as well.

I could be wrong though of course, so I'd be interested to learn what your findings are.

**Comment by RebeccaGw** [comment]
Thank you for your response :)

And yeah, but don't you still have to list the cookies?

Do you know what they are?

**Comment by bhadaway** [comment]
To make sure that you're GDPR compliant, I would do this:

1. Install this plugin:

https://wordpress.org/plugins/cookie-notice/

Or another if it doesn't suit your needs:

https://wordpress.org/plugins/search/cookies/

2. Then, run your site through this checker:

https://www.cookiemetrix.com/

Unless you're running a massive site where you might need to enlist the help of a lawyer, I really think this would be enough due diligence on your part.
