### ISSUE TITLE
Allow List Email

### ISSUE THREAD

**Issue by web-dev-18** [bhadaway/stop-spammers#75]
Greetings,

How do I add any email that comes from a domain email into the Allow List? I am not sure how the wild card email works, is it with an asterisk?   *@mydomain.com

Thank you.

**Comment by bhadaway** [comment]
I adopted this plugin and I'm actually not 100% sure.

Can you try these variations:

@mydomain.com
*mydomain.com
mydomain.com

It might not be possible, unfortunately.

Does this need to be future-proofed because there could be potentially hundreds or more of company accounts, making whitelisting one by one very tedious?

Will there be a wide variety of IPs or perhaps you could whitelist your company network?
