### ISSUE TITLE
Everyone has an ip server

### ISSUE THREAD

**Issue by youropportunity** [bhadaway/stop-spammers#8]
Hello, I do not know if the issue, but all users, including admin, have an ip server web page, so in this state it is unusable.

But otherwise great work

Paul

**Comment by bhadaway** [comment]
Hey Paul,

I'm not sure that I understand what you're asking. Do you mind explaining a bit more?

Thank you.

**Comment by youropportunity** [comment]
Hello, I mean, all the log report is from the same IP, from my server's IP. Maybe this is a cache? I use the varnish cache.

**Comment by bhadaway** [comment]
I see. Are you using Cloudflare? If so, you'll need to install a fix to restore IPs:

https://support.cloudflare.com/hc/sections/200805497-Restoring-Visitor-IPs

Thanks

**Comment by youropportunity** [comment]
Hi i have this problem on the subdomain where i think cloudflare does not work but i try cloudflare fix, 

thank you for your time

**Comment by bhadaway** [comment]
If you're on a shared hosting server, you're probably out of luck.

If you're on a VPS or dedicated server, you should be able to find a solution.

Whatever your hosting server situation, if you're able to implement the IP fix, it should cover your whole account, all: domains, subdomains, add-on domains, etc.

**Comment by stodorovic** [comment]
If you use Varnish cache, it's server IP address and real IP is `$_SERVER['HTTP_X_FORWARDED_FOR']`. It's possible to add simple PHP snippet into `wp-config.php` or make simple plugin (installed in mu-plugins because it runs before other plugins).

From other side, it's possible to improve function https://github.com/bhadaway/stop-spammers/blob/master/stop-spammer-registrations-new.php#L260-L263

My opinion is that's better to we make simple mu-plugin. (it covers all plugins) If you can wait few days, I'll create simple PHP file and you need only to upload it into `wp-content/mu-plugins`.

**Comment by youropportunity** [comment]
Hello, thank you very much. I tried to insert "$_SERVER['HTTP_X_FORWARDED_FOR']; " at the end wp-config.php  (Or where it is best to insert ?)
And I'm waiting for a change, in the final it might be better to deactivate the varnish cache on the server (KVM). Unfortunately I do not see the change, still a log report from the ip server

**Comment by stodorovic** [comment]
If you want to add custom code into `wp-config.php` (not at the end), you should add it between:

```php
/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 *
 * For information on other constants that can be used for debugging,
 * visit the Codex.
 *
 * @link https://codex.wordpress.org/Debugging_in_WordPress
 */
```
AND
```php
/* That's all, stop editing! Happy blogging. */
```
**The code at the end isn't functional.**

Possible code is:
```php
if ( ! empty( $_SERVER['HTTP_X_FORWARDED_FOR'] )
     && preg_match( '/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/', $_SERVER['HTTP_X_FORWARDED_FOR'] ) )
        $_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_X_FORWARDED_FOR'];
```

## Please be careful and make backup of `wp-config.php` before.
PS. I'll remove this code in next couple hours because it could be dangerous for someone which doesn't understand all details.

**Comment by youropportunity** [comment]
Hoho, yes i am not a professional, so backup and / or cancel the varnish cache on the server, this for me makes support for my hosting, I would break the server hehe (sorry my english

**Comment by stodorovic** [comment]
If you add previous code before:

```php
/* That's all, stop editing! Happy blogging. */
                                  
/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */  
require_once(ABSPATH . 'wp-settings.php');
```
It's fine and it should work. I want to remove previous comment because I had bad experience with other people which just see the code and they are trying to add it without reading all comments.
I hope that you copied the code, I just removed it.

Varnish could be helpful if you have some warm or preload script on your KVM. Something like this:

https://github.com/sys0dm1n/varnish-cache-warmer/blob/master/varnish-cache-warmer.sh
https://www.htpcguides.com/smart-warm-up-your-wordpress-varnish-cache-scripts/
From other side, if you have W3TC or Supercache you can try to enable real cron job on your server and enable preloading. In this case, you can cancel varnish.

http://support.hostgator.com/articles/how-to-replace-wordpress-cron-with-a-real-cron-job
So, it's also out of topic. I'll remove it later.

**Comment by youropportunity** [comment]
so i did put your code after ('WP_DEBUG', false); and i see change in log report - now not all log reports from the server ip - Great - Big Thank you

**Comment by bhadaway** [comment]
Thank you @stodorovic for the solution. :)
