### ISSUE TITLE
Allow List Emails Isn't Working

### ISSUE THREAD

**Issue by vitamincee** [bhadaway/stop-spammers#90]
Hello,
Users who have their emails on our allow list are still getting blocked. I'm not entirely sure why - it appears this functionality isn't working on our setup.

Do you have any ideas why it's ignoring this?

Thanks!

**Comment by bhadaway** [comment]
Double-check that their IPs aren't on the block list, and make sure to whitelist their IPs as well.

**Comment by vitamincee** [comment]
IPs are not in the block list, but I know for certain that one of them uses a VPN. The IP changes every time they access the site and they're blocked each time. They are logged in and using the same email which is whitelisted.

**Comment by bhadaway** [comment]
Yeah, VPNs are always going to run into issues with spam filters.

Have you tried whitelisting his username? That might work.

**Comment by vitamincee** [comment]
Nope, but I will try that now. Thanks!

**Comment by vitamincee** [comment]
Hi I whitelisted her username and that also did not work. Any other ideas?

**Comment by bhadaway** [comment]
While I certainly respect people's right to use a VPN, and understand there are many legitimate reasons to use a VPN, an unavoidable fact remains that a VPN to Stop Spammers, is like what kryptonite is to Superman.

Pretty much any IP address from a virtual private network is going to have been abused and find its way onto many blacklists. And since Stop Spammers relies primarily on IP addresses, that's pretty much a deal-breaker.

I'm not really sure Stop Spammers is going to work for you. You should check out:

https://wordpress.org/plugins/wordfence/
