### ISSUE TITLE
Block user registration by domain?

### ISSUE THREAD

**Issue by JorritHimself** [bhadaway/stop-spammers#91]
I am yet to see a record in my log where Stop Spammers denied registration of a user.
I have had plenty 'passed registration' from e.g.,
@maleenhancement.club
@dietingadvise.club
@forum.britted.com
@walletonlineshop.com
etc, etc.

Why is the plugin not picking up on this? Are only individual addresses or IPs blocked, rather than entire spammy domains? Are there settings that I should change?

I have also seen records of bad bots e.g.,:
2019/04/14 17:43:36	--	58.218.213.162 
   	--	/image/shell.asp/crazy8.jpg	404 on Exploit Attempt /image/shell.asp/crazy8.jpg .asp
2019/04/14 17:43:33	--	58.218.213.162 
   	--	/image/shell.asp/crazy8.jpg	404 on Exploit Attempt /image/shell.asp/crazy8.jpg .asp
2019/04/14 17:43:31	--	58.218.213.162 
   	--	/image/shell.asp/crazy8.jpg	404 on Exploit Attempt /image/shell.asp/crazy8.jpg .asp
2019/04/14 17:43:29	--	58.218.213.162 
With this sort of attempts filling up the entire log record of the plugin. 
Is there a way/setting to block the IP when this is noticed? I have added this one to my IP deny manger in cPanel, but I'm sure I'm not going to win the war against bots if I have to manually target them one by one.

**Comment by bhadaway** [comment]
If nothing is getting blocked, it sounds like Stop Spammers might not be able to accurately detect IP addresses. Are you using Cloudflare or similar?

**Comment by JorritHimself** [comment]
I am using Cloudfare, yes.
I assumed the plugin would look at email addresses or domains.

**Comment by bhadaway** [comment]
When it comes to priority in Stop Spammers, IPs are king. If IPs haven't been restored and generally all traffic is seen as coming from the same IP(s), then when you log in as the admin, it's whitelisting that IP, and therefore any bad actor that comes along after will get past the filter because they're seen as coming from the same IP as well.

Please see: https://support.cloudflare.com/hc/sections/200805497-Restoring-Visitor-IPs

If you're on a shared host, it may not be possible, but you could always ask support.

If that's the case, you can also check out this security plugin, which is safe to use with Stop Spammers:

https://wordpress.org/plugins/wordfence/

**Comment by JorritHimself** [comment]
I've now actually found the option to block entire domains from commenting and subscribing, in your block lists options.
This is a better solution for me, and good enough if i can manually block an entire domain in once rather than individual users.

**Comment by bhadaway** [comment]
Okay, good to hear it's solved. :)
