### ISSUE TITLE
How to block spammers by username

### ISSUE THREAD

**Issue by retroriff** [bhadaway/stop-spammers#96]
Hello,

during the last weeks I have been spammed by users with usernames as:

“chat Mary and Dawn http://www.infozones.ru”
“meet Lauren and Bertha http://www.project1304737.tilda.ws”
"chat Beverly and Deborah www.litkurort.com"

They have emails as abrahamdavalos@yahoo.com, ymsmk@hotmail.co.uk…

How could we stop registering to spammers with an URL in their username?

Thank you

**Comment by bhadaway** [comment]
Use: _Stop Spammers > Block Lists > Spam Words List_

**Comment by retroriff** [comment]
Hello, I already have added date, chat and meet into this Spam Words List but I continue receiving spam like this:

Username: date Dana and Candice www.berloga55.com

**Comment by bhadaway** [comment]
Hi retroriff,

Just to verify, when you say you continue to receive, you mean that they're successfully registering or leaving a comment?

Thanks

**Comment by retroriff** [comment]
I mean registering.

**Comment by retroriff** [comment]
> Hi retroriff,
> 
> Just to verify, when you say you continue to receive, you mean that they're successfully registering or leaving a comment?
> 
> Thanks

I mean registering.

**Comment by jseutens** [comment]
I'm looking for a plugin that can block these users , found this plugin as recommendation , but see that these users are not blocked.
Is there a way to block users if they use a DOT (.) or www. in there username ? that would block all of these immediately, let them think they registered but don't send out the email and get them into a user group that is named blocked with no permissions.

**Comment by bhadaway** [comment]
@retroriff — Okay, I think I understand the confusion now.

1. Blocking registrations. You can only block what info and patterns you have access to at the time of registration, so that would be usernames, email addresses, domains, and IP addresses.

2. Blocking spam comments. So, when you block spammy words, that can't prevent them from actually registering, it'll only block their comment at the point where they try and actually use those words.

Does that make sense? I understand that it makes it very difficult to then block the actual registration, because unless they're using really obvious patterns, you would cast too wide of a net and end up blocking legit users too.

Speaking of which, _date_, _chat_, and _meet_ are too broad to be blocked. I would remove those and instead block more obvious and specific things like _infozones_ and _litkurort_.

This probably isn't the answer you want, but you'll just need to keep an eye on it, and keep refining your settings. It's not a perfect science and there's no quick fix.

**Comment by retroriff** [comment]
Hello, thanks for the clarifications. However these spammers use a different domain (infozones, litkurort ) for each user. They have thousands of spammy domains, so these option does not work. Blocking broader words such as "date, chat, and meet" should be enough. I don't care if a few usernames may be affected. I blocked some IPs and we are not receiving spam anymore, although they usally send their massive spam during a couple of days and come back after some weeks.

**Comment by bhadaway** [comment]
Yes, you'll find that they're going to constantly change IPs as well.

You may just have to make registration more strict, requiring CAPTCHA entry, email verification, or even that you have to manually approve new users.

Here are some plugins that you can add, that all compliment each other and work together with Stop Spammers:

https://wordpress.org/plugins/akismet/
https://downloads.wordpress.org/plugin/theme-my-login.6.4.17.zip
https://wordpress.org/plugins/wordfence/
